name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.KEY }}

      - name: Deploy to VM
        run: |
          ssh -i ${{ secrets.KEY }} opc@168.138.40.117 "cd /path/to/your/project && git pull && docker-compose up --build -d tripsketch"
