name: CI

on:
  push:
    branches:
      - feature/*
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "zulu"

      - name: Set up Kotlin
        uses: fwilhe2/setup-kotlin@0.9.0
        with:
          kotlin-version: "1.9.22"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "zulu"

      - name: Set up Kotlin
        uses: fwilhe2/setup-kotlin@0.9.0
        with:
          kotlin-version: "1.9.22"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Linting
        run: ./gradlew ktlintCheck

      - name: Run Code Formatting Check
        run: ./gradlew spotlessCheck

      - name: Run Spring Boot Check
        run: ./gradlew check
